# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'batiments',
            },
        ),
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'composantes',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'diplomes',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaires', models.CharField(max_length=5000)),
                ('anneeuniversitaire', models.IntegerField()),
                ('anneeetude', models.IntegerField()),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Composante')),
            ],
            options={
                'db_table': 'formations',
            },
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=20)),
                ('civilite', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'individus',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'niveaux',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeuniversitaire', models.IntegerField()),
                ('anneeetude', models.IntegerField()),
                ('effectif', models.IntegerField()),
                ('composante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formation.Composante')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formation.Diplome')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Niveau')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porte', models.CharField(max_length=250)),
                ('etage', models.CharField(max_length=250)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formation.Batiment')),
            ],
            options={
                'db_table': 'salles',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateTimeField()),
                ('find', models.DateTimeField()),
                ('visiteguidee', models.BooleanField()),
                ('remarques', models.CharField(max_length=5000)),
                ('participants', models.IntegerField()),
                ('manipulations', models.BooleanField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Formation')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Salle')),
            ],
            options={
                'db_table': 'seances',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=2)),
                ('code_commune', models.IntegerField()),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Individu'),
        ),
        migrations.AddField(
            model_name='formation',
            name='diplome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Diplome'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Niveau'),
        ),
        migrations.AddField(
            model_name='formation',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Promotion'),
        ),
        migrations.AddField(
            model_name='formation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Site'),
        ),
        migrations.AddField(
            model_name='formation',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.Theme'),
        ),
        migrations.AddField(
            model_name='composante',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formation.Site'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formation.Site'),
        ),
    ]
